builder/urls.py
from django.urls import path
from . import views

app_name = 'builder'
urlpatterns = [
    path('', views.index, name='index'),

    path('signup/', views.SignUp.as_view(), name='signup'),

    path('search/', views.search, name='search'),  # search field
    path('search/result/', views.result, name='result'),  # results of searching
    path('search/result/<str:card_id>/', views.detail, name='detail'),  # detail of card

    path('players/', views.players, name='players'),  # all players
    path('player/<int:player_id>/', views.player, name='player'),  # detail of player

    path('decks/', views.decks, name='decks'),  # all decks
    path('deck/<int:deck_id>/', views.deck, name='deck'),  # detail of deck

    path('create_deck/<str:card_id>/', views.create_deck, name='create_deck'),
    path('create_deck_submit/<str:card_id>/', views.create_deck_submit, name='create_deck_submit'),
    path('add_to_deck/<str:card_id>/', views.add_to_deck, name='add_to_deck'),
    path('add_to_deck_submit/<str:card_id>/', views.add_to_deck_submit, name='add_to_deck_submit'),

    path('delete_card/<int:id>/', views.delete_card, name='delete_card'),
    path('delete_deck/<int:id>/', views.delete_deck, name='delete_deck'),

    path('new_comment/<int:deck_id>/', views.new_comment, name='new_comment'),
    path('new_comment_submit/<int:deck_id>/', views.new_comment_submit, name='new_comment_submit'),

]

deckbuilder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [

    path('', include('builder.urls')),
    path('builder/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

builder/models.py
from django.contrib.auth.models import User
from django.db import models


class Deck(models.Model):
    deck_name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_cards(self):
        return Card.objects.filter(deck=self)

    def get_comments(self):
        return Comment.objects.filter(to_deck=self)

    def __str__(self):
        return self.deck_name


class Card(models.Model):
    card_id = models.CharField(max_length=100)
    name = models.CharField(max_length=150)  # string
    manaCost = models.CharField(max_length=100, null=True)
    colors = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=30)
    cmc = models.IntegerField()  # int - converted mana cost
    rarity = models.CharField(max_length=20)
    text = models.CharField(max_length=1000, null=True)
    flavor = models.CharField(max_length=1000, null=True)
    imgUrl = models.CharField(max_length=1000)
    artist = models.CharField(max_length=100)
    number = models.IntegerField(null=True)  # Some cards dont have number???
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)

    def __str__(self):
        return '%s, {%s}' % (self.name, self.cmc)


class Comment(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=500)
    added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    to_deck = models.ForeignKey(Deck, on_delete=models.CASCADE)

    def __str__(self):
        return '%s, %s' % (self.title, self.text)

builder/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Deck, Card, Comment
import requests
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate


# --------------------------------   MAH FUNCS

# Name says it all
def gimme_card_data_by_id(card_id):
    response = requests.get('https://api.magicthegathering.io/v1/cards/%s' % card_id)
    card_data = response.json()
    return card_data['card']  # Bc its returning {"card":{...stuffiwant...}}


# from card_id it adds card into DB & returns card
def create_card_return(card_id, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    c_data = gimme_card_data_by_id(card_id)

    card = Card(card_id=c_data['id'], name=c_data['name'], colors=None,
                type=c_data['type'], cmc=c_data['cmc'], rarity=c_data['rarity'], text=None,
                flavor=None, artist=c_data['artist'], imgUrl=c_data['imageUrl'],
                number=None, deck=deck)
    if 'text' in c_data:
        card.text = c_data['text']
    if 'colors' in c_data:
        card.colors = c_data['colors']
    if 'flavor' in c_data:
        card.flavor = c_data['flavor']
    if 'manaCost' in c_data:
        card.manaCost = c_data['manaCost']
    if 'number' in c_data:
        card.number = c_data['number']

    card.save()
    return card


# --------------------------------  signup
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    # for all generic class-based views the urls are not loaded when the file is imported, so we have to use the lazy
    # form of reverse to load them later when they’re available
    template_name = 'registration/signup.html'


# --------------------------------   VIEWS
# Main page
def index(request):
    return render(request, 'index.html')


# def home(request):
#   return render(request, 'home.html')


# Just leads to page with 'search card' field
def search(request):
    return render(request, 'search/index.html')


# Cards found by 'q'
def result(request):
    q = request.POST['q']
    response = requests.get('https://api.magicthegathering.io/v1/cards?name=%s' % q)
    c_data = response.json()['cards']
    return render(request, 'search/result.html', {'q': q, 'cards_data': c_data})


# Detail of card
def detail(request, card_id):
    c_data = gimme_card_data_by_id(card_id)
    img_url = 'http://gatherer.wizards.com/Handlers/Image.ashx?id=%s&type=card' % card_id
    return render(request, 'search/detail.html', {'card_data': c_data, 'url_img': img_url})


# All decks
def decks(request):
    ds = Deck.objects.all()
    return render(request, 'deck/decks.html', {'decks': ds})


# Detail of deck
def deck(request, deck_id):
    d = Deck.objects.get(id=deck_id)
    c = d.get_cards()
    userid = None
    if request.user.is_authenticated:
        userid = request.user.id
    comments = Comment.objects.filter(to_deck=deck_id)
    return render(request, 'deck/deck.html', {'deck': d, 'cards': c, 'userid': userid, 'comments': comments})


# Leads to 'add card to existing deck' and sending card_id & all decks
def add_to_deck(request, card_id):
    decks = Deck.objects.all()
    userid = None
    if request.user.is_authenticated:
        userid = request.user.id
    return render(request, 'add_card/to_existing.html', {'card_id': card_id, 'decks': decks, 'userid': userid})


# Saving the deck from 'add card to existing deck'
def add_to_deck_submit(request, card_id):
    deck_id = request.POST['deck_id']

    d = get_object_or_404(Deck, pk=deck_id)
    create_card_return(card_id, deck_id)
    d.save()

    return HttpResponseRedirect(reverse('builder:decks'))


# Leads to 'add card to new deck' and sending card_id
def create_deck(request, card_id):
    players = User.objects.all()
    userid = None
    if request.user.is_authenticated:
        userid = request.user.id
    return render(request, 'add_card/to_new.html', {'card_id': card_id, 'players': players, 'userid': userid})


# Saving the new deck from 'add card to new deck'
def create_deck_submit(request, card_id):
    p_id = request.POST['player_id']
    p = get_object_or_404(User, pk=p_id)
    d_name = request.POST['deck_name']
    d = Deck(deck_name=d_name, owner=p)
    d.save()
    create_card_return(card_id, d.id)
    return HttpResponseRedirect(reverse('builder:decks'))


def delete_deck(request, id):
    Deck.objects.filter(id=id).delete()
    return HttpResponseRedirect(reverse('builder:decks'))


def delete_card(request, id):
    Card.objects.filter(id=id).delete()
    return HttpResponseRedirect(reverse('builder:decks'))


def players(request):
    players = User.objects.all()
    return render(request, 'player/players.html', {'players': players})


def player(request, player_id):
    player = User.objects.get(pk=player_id)

    decks = Deck.objects.filter(owner=player_id)
    userid = None
    if request.user.is_authenticated:
        userid = request.user.id
    return render(request, 'player/player.html', {'player': player, 'decks': decks, 'userid': userid})


def new_comment(request, deck_id):
    userid = None
    if request.user.is_authenticated:
        userid = request.user.id
    return render(request, 'comment/new_comment.html', {'userid':userid, 'deck_id':deck_id})


def new_comment_submit(request, deck_id):
    text = request.POST['text']
    title = request.POST['title']
    deck = get_object_or_404(Deck, pk=deck_id)
    user = None
    if request.user.is_authenticated:
        user = request.user
    comment = Comment(title=title, text=text, author=user, to_deck=deck)
    comment.save()
    return HttpResponseRedirect(reverse('builder:index'))

builder/templates/base.html
<html>
    <head>
        <style>
        table {
            border-collapse: collapse;
            width: 98%;
        }
        .btn {
            display: inline-block;
            padding: 6px 12px;
            margin-bottom: 0;
            font-size: 14px;
            font-weight: 400;
            line-height: 1.42857143;
            text-align: center;
            white-space: nowrap;
            vertical-align: middle;
            -ms-touch-action: manipulation;
            touch-action: manipulation;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            background-image: none;
            border: 1px solid transparent;
            border-radius: 4px;
        }
        </style>
    </head>
    <body style="width: 98%; height: 100%; background-color:161616; font-family: Ubuntu;
            "text=F6F6F6 link="A6A6A6" vlink="767676" alink="FFFFFF">
        <div>
            <table style="width:100%">
                <col width="20%">
                <col width="80%">
                <tr>
                    <th colspan="2">
                        <a href="{% url 'builder:index'%}" style="text-decoration: none"><h1>☣DECKBUILDER☣</h1></a>
                        <a href="https://magic.wizards.com/en" style="text-decoration: none"><h3> Magic: The Gathering </h3></a>
                    </th>
                </tr>
                <tr>
                    <th style="vertical-align: top;"><br><br>

                        {% if user.is_authenticated %}
                            Hi {{ user.username }}! <br><br>

                        {% else %}
                            <p>You are not logged in</p>
                            <a href="{% url 'login' %}"><button class="btn">Login</button></a><br><br>
                            <a href="/signup"><button class="btn">Signup</button></a><br><br><br><br><br><br>
                        {% endif %}

                        <a href="/search"><button class="btn">Search cards</button></a><br><br>
                        <a href="/decks"><button class="btn"type="submit">View all decks</button></a><br><br>
                        <a href="/players"><button class="btn"type="submit">View players</button></a><br><br><br><br>

                        {% if user.is_authenticated %}
                            <p><a href="{% url 'logout' %}"><button class="btn">Logout</button></a></p><br><br>
                        {% endif %}

                    </th>
                    <th style="vertical-align: middle;">
                        <table border="0" >
                            <tr>
                                <th>
                                    {% block content %}

                                    {% endblock %}
                                </th>
                            </tr>
                        </table>
                    </th>
                </tr>
            </table>
        </div>
    </body>
</html>

builder/templates/deck.html
 {% extends "base.html" %}
 {% block content %}

 <table>
     <col width="70%">
     <col width="30%">
   <tr>
    <th>
      <span style="font-weight:normal">{{deck.owner.username}}'s</span>
 <h2>{{deck.deck_name}}</h2>
     {% for card in cards %}
      <li>
       <a href="{% url 'builder:detail' card.card_id %}" style="text-decoration: none">
        {{card.name}}
       </a>
          {% if userid%}
          {% if userid == deck.owner.id%}
       -
       <a href="{% url 'builder:delete_card' card.id %}" style="text-decoration: none; font-weight:normal;" >
        ☠
       </a>
          {% endif%}
          {% endif%}
      </li>
     {% endfor %}
     <br><br><br><br><br>

          {% if userid%}
          {% if userid == deck.owner.id%}
       <span style="font-weight:normal;">delete deck</span>
       <a href="{% url 'builder:delete_deck' deck.id %}" style="text-decoration: none" >
     <span style="font-weight:normal;">
      <h1>☠</h1>
     </span>
            {% endif%}
          {% endif%}
      </a>
    </th>
    <th>
        Comments:<br><br><br>
    {% for comment in comments%}
        <span style="font-weight:normal;">
            {{comment.author}}
            : <br>{{comment.text}}</span>
    {% endfor%}
    </th>
   </tr>
 </table>
 {% endblock %}

builder/templates/home.html
 {% extends "base.html" %}
 {% block title %}Home{% endblock %}
 {% block content %}
 <br><br><br>
 <span style="font-weight:normal">
OH, HI MARK
 </span>

 {% endblock %}

builder/templates/index.html
 {% extends "base.html" %}
 {% block content %}


 <br><br><br>
 <strong>HELLO THERE</strong><br><br>
 <span style="font-weight:normal">

  What you can do as anonym:<br>
  Login, signup, search cards, view decks, cards in it and comments<br><br>
  What you can do as user:<br>
  All above, add card into your deck, create new deck, comment deck, logout

<br><br><br><br>
  ENJOY


 </span>

 {% endblock %}

builder/templates/player.html
 {% extends "base.html" %}
 {% block content %}
{{player.login}}<br><br>
 <table>
  <tr>
   <th>
     {% for deck in decks %}
        <li>
         <a href="{% url 'builder:deck' deck.id %}" style="text-decoration: none">
   <strong>{{deck.deck_name}}</strong></a>  -
   <a href="{% url 'builder:delete_deck' deck.id %}" style="text-decoration: none" ><span style="font-weight:normal">☠</span></a>

        </li>
    {% endfor %}

   </th>
  </tr>
 </table>

 {% endblock %}